---
title: "Lab One, Part One"
author: "PUT YOUR GROUP NAMES HERE"
date: "PUT THE SUBMISSION DATE HERE"
output:
  pdf_document:
    toc: true
    number_sections: true
    toc_depth: 3
---

# Part 1: Foundational Exercises
## Professional Magic

Based on the given, we know that the two coins are represented by Bernoulli Random Variables. To determine whether or not it is indeed magic, we designed a test to flip the two coins three times and record the test statistics of the number of heads shown. In the case of a fair coin toss, our Null Hypothesis (Ho) is p = 1/2. Since we are flipping 2 coins three times, we would have at most 6 heads shown. So we plan to reject our Null Hypothesis if our test statistics is 0 or 6.

a. Here we want to calculate the type 1 error rate. Type 1 error rate is refers to as the probability of rejecting the Null Hypothesis (Ho) given that the Null Hypothesis is True.

$$
  P(Rejecting\ H_o\ |\ H_o)
$$

Let the test statistics be T = (X_1 + Y_1) + (X_2 + Y_2) + (X_3 + Y_3), X_i and Y_i takes on values in {0, 1}

$$
  Rejection\ Region: T = [0, 6]
$$
$$
  P(Rejecting\ H_o\ |\ H_o) = P[(T = 0)\ U\ (T = 6)\ when\ T\ is \ Bernouli(p/2)]
  
$$
Since each X, Y coin toss is independence:
$$
  P(Rejecting\ H_o\ |\ H_o) = P[(T = 0)] + P[(T = 6)]\ Independence
  
$$
Expanding the probability, and subsitute p=1/2 into the system since we are given Ho: p=1/2. We apply multiplication for 3 coin tosses here since each (X, Y) pairs are IID, and we have three pairs
$$
  P[(T = 0)] = [X1 = 0, Y1= 0, X2=0, Y2=0, X3=0, Y3=0] = (p/2)^3 = (1/4)^3 = (1/4)^3 = 1/64
$$
$$
  P[(T = 6)] = [X1 = 1, Y1= 1, X2=1, Y2=1, X3=1, Y3=1] = (p/2)^3 = (1/4)^3 = (1/4)^3 = 1/64
$$
$$
  P(Rejecting\ H_o\ |\ H_o) = 1/64 + 1/64 = 1/32 
$$

b. Here we want to calculate the statistical power of our test for the alternate hypothesis. Statistical Power is related to Type 2 error rate and is refers to as the probability of supporting the Alternate Hypothesis (Ha) given that the Alternate Hypothesis is True. and the statistical power is just 1 - type 2 error rate

$$
  P(Supporting\ H_a\ |\ H_a)
$$
We are given that Ha: p=3/4, and that our rejection region is [0, 6]


$$
  P(# of heads in the rejection region | Ha) = P(# of  heads in [0, 6] | Ha)

$$


Since each X, Y coin toss is independence:
$$
  P(Supporting\ H_a\ |\ H_a) = P[(T = 0)] + P[(T = 6)]\ Independence
$$


Expanding the probability, and subsitute p=3/4 into the system since we are given Ha: p=3/4. We apply multiplication for 3 coin tosses here since each (X, Y) pairs are IID, and we have three pairs
$$
  P[(T = 0)] = [X1 = 0, Y1= 0, X2=0, Y2=0, X3=0, Y3=0] = (p/2)^3 = (3/8)^3 = 27/512
$$


$$
  P[(T = 6)] = [X1 = 1, Y1= 1, X2=1, Y2=1, X3=1, Y3=1] = (p/2)^3 = (3/8)^3  = 27/512
$$



So the statistical power, or tje probability of not making a type 2 error is computed as follow
$$
  Statistical Power = 27/512 + 27/512 = 27/256 \approx 0.105
$$


\newpage
## Wrong Test, Right Data
Let X be the Random Variable for how much customers like the regular website. Let Y be the Random Variable for how much customers like the mobile website. The scale of measurement is on the 5 points Likert scales. Given that Likert scales is an ordinal scale, if we are using the paried t-test, we would violate the assumption that the t-test uses a metric scale. To calculate t-test statistics in the paired t-test, we know that we need to calculate an expected value and the sample variation for both random variable X, Y. For that, the scale has to be continuous. The Likert scale, being an ordinal scale, has no objective variation between one value to another. This would give you a larger test statistics t, making our test sample to fall into the rejection region, which would increase the type 1 error rate. To correct for this, we suggest Wilcoxon Sign-Rank Test because the two samples are dependent.


\newpage
## Test Assumptions
### World Happiness

### Legislators

### Wine and health

### Attitudes toward the religious

